// Hand-mirrored from app/schemas (Pydantic). Replace via `npm run gen-types`
// once `mobile/openapi.json` is regenerated by scripts/export_openapi.sh.

export type UUID = string;
export type IsoDate = string;
export type IsoDateTime = string;

// auth
export interface LoginRequest {
  email: string;
  password: string;
}
export interface TokenResponse {
  token: string;
  expires_at: IsoDateTime;
}

// plan / workouts
export type WorkoutStatus = 'planned' | 'moved' | 'skipped' | 'done';
export type WorkoutFamily = 'running' | 'strength' | 'other';

export interface PlannedWorkoutSnapshot {
  type: string;
  family: string;
  distance_mi: string | null;
  duration_min: number | null;
  title: string;
  target_pace: string | null;
  target_hr_zone: string | null;
}

export interface PlannedActualOut {
  /** Actual distance in miles, derived from CompletedWorkout.distance_m (m → mi). */
  distance_mi: string | null;
  duration_s: number;
  started_at: string; // ISO datetime
}

export interface PlannedWorkoutOut {
  id: UUID;
  cycle_id: UUID;
  scheduled_date: IsoDate;
  original_date: IsoDate;
  week_number: number;
  type: string;
  family: string;
  status: WorkoutStatus;
  duration_min: number | null;
  distance_mi: string | null;
  target_pace: string | null;
  target_hr_zone: string | null;
  title: string;
  description_md: string;
  intent_md: string;
  original_snapshot: PlannedWorkoutSnapshot | null;
  /** Populated by /plan/week when a matched CompletedWorkout exists; otherwise null. */
  actual: PlannedActualOut | null;
}

export interface CompletedWorkoutOut {
  id: UUID;
  garmin_activity_id: number;
  activity_date: IsoDate;
  started_at: IsoDateTime;
  activity_type: string;
  family: string;
  duration_s: number;
  distance_m: string | null;
  avg_hr: number | null;
  max_hr: number | null;
  avg_pace_s_per_km: number | null;
  elevation_gain_m: string | null;
  calories: number | null;
}

export interface ReconciliationOut {
  id: UUID;
  planned_id: UUID | null;
  completed_id: UUID | null;
  match_confidence: string | null;
  deviation_notes_md: string;
  agent_review_md: string | null;
  agent_reviewed_at: IsoDateTime | null;
}

export interface WorkoutDetailOut {
  planned: PlannedWorkoutOut | null;
  completed: CompletedWorkoutOut | null;
  reconciliation: ReconciliationOut | null;
}

export interface CycleOut {
  id: UUID;
  name: string;
  sequence: number;
  race_name: string;
  race_date: IsoDate;
  start_date: IsoDate;
  end_date: IsoDate;
}

export interface CycleProgress {
  week: number;
  total_weeks: number;
  days_to_race: number;
}

export interface PlanCurrentOut {
  plan_name: string;
  plan_id: UUID;
  active_cycle: CycleOut | null;
  cycle_progress: CycleProgress | null;
}

export interface DayWorkouts {
  date: IsoDate;
  workouts: PlannedWorkoutOut[];
}

export interface WeekOut {
  week_start: IsoDate;
  days: DayWorkouts[];
}

export interface TodayOut {
  date: IsoDate;
  workouts: PlannedWorkoutOut[];
  coach_brief: string | null;
}

// move flow
export interface MoveRequest {
  new_date: IsoDate;
}
export interface WorkoutEdit {
  workout_id: UUID;
  field: 'scheduled_date' | 'status';
  new_value: string;
}
export type AdapterOptionId = 'option_a' | 'option_b';
export interface AdapterOption {
  id: AdapterOptionId;
  label: string;
  tradeoff: string;
  edits: WorkoutEdit[];
  rationale: string;
}
export interface ProposalOut {
  proposal_id: UUID;
  summary: string;
  options: AdapterOption[];
  /** Lifecycle state from the backend: "pending" | "applied" | "discarded". */
  state?: string | null;
}
export type ApplyChoice = AdapterOptionId | 'just_move' | 'cancel';
export interface ApplyMoveRequest {
  proposal_id: UUID;
  choice: ApplyChoice;
}

// chat
export interface ChatMessageOut {
  id: UUID;
  role: 'user' | 'assistant';
  content_md: string;
  created_at: IsoDateTime;
  proposal: ProposalOut | null;
}
export interface ChatHistoryOut {
  messages: ChatMessageOut[];
}
export interface PostChatRequest {
  message: string;
}
export interface PostChatResponse {
  reply_md: string;
  proposal: ProposalOut | null;
}
export interface ChatProposalApplyRequest {
  proposal_id: UUID;
  choice: ApplyChoice;
}

// metrics
export interface DailyMetricOut {
  id: UUID;
  metric_date: IsoDate;
  sleep_score: number | null;
  sleep_duration_s: number | null;
  hrv_overnight_ms: string | null;
  resting_hr: number | null;
  body_battery_high: number | null;
  body_battery_low: number | null;
  training_readiness: number | null;
  training_status: string | null;
}

// garmin
export interface GarminReauthRequest {
  email: string;
  password: string;
}
export interface GarminStatusOut {
  needs_reauth: boolean;
  last_sync: IsoDateTime | null;
  last_error: string | null;
  last_error_at: IsoDateTime | null;
}
export interface SyncReportOut {
  synced_activities: number;
  synced_metrics: number;
  errors: string[];
}

// edit / reschedule-original
export interface EditWorkoutRequest {
  type?: string;
  distance_mi?: number | null;
  duration_min?: number | null;
  title?: string;
  description_md?: string;
  intent_md?: string;
}

export interface RescheduleOriginalRequest {
  new_date: IsoDate;
}

export interface RescheduleOriginalResponse {
  new_workout_id: UUID;
  proposal: ProposalOut;
}

// Program tab
export type WeekStatus = 'done' | 'partial' | 'current' | 'upcoming' | 'skipped';

export interface WeekRollup {
  week_number: number;
  week_start: IsoDate;
  week_end: IsoDate;
  planned_count: number;
  done_count: number;
  skipped_count: number;
  moved_count: number;
  planned_mi: string;   // Decimal serialized as string
  actual_mi: string;
  is_cutback: boolean;
  is_peak: boolean;
  has_race: boolean;
  status: WeekStatus;
}

export interface CycleFull extends CycleOut {
  peak_week_target: number | null;
  race_planned_id: UUID | null;
  weeks: WeekRollup[];
}

export interface PlanFullOut {
  plan_name: string;
  plan_id: UUID;
  start_date: IsoDate;
  end_date: IsoDate;
  cycles: CycleFull[];
}

export type MilestoneKind = 'peak' | 'race' | 'decision';

export interface NextMilestone {
  kind: MilestoneKind;
  label: string;
  date: IsoDate;
}

export interface PeakWeekSummary {
  week_number: number;
  planned_mi: string;
  long_run_mi: string | null;
}

export interface PlanStatsOut {
  scope: 'cycle' | 'plan';
  cycle_id: UUID | null;
  on_plan_pct: number;
  done_count: number;
  skipped_count: number;
  planned_to_date_count: number;
  planned_mi: string;
  actual_mi: string;
  streak_days: number;
  next_milestone: NextMilestone | null;
  peak_week: PeakWeekSummary | null;
  computed_at: IsoDateTime;
}

// Feat A — mark complete
export interface LogCompletedRequest {
  duration_min: number;
  distance_mi?: number | null;
  avg_pace_str?: string;   // "mm:ss" — backend converts
  avg_hr?: number;
  notes?: string;
}

export interface LogCompletedResponse {
  planned: PlannedWorkoutOut;
  completed: CompletedWorkoutOut;
  reconciliation: ReconciliationOut;
}

// link-completed
export interface CandidateOut {
  completed_id: UUID;
  activity_date: IsoDate;
  activity_type: string;
  distance_mi: number | null;
  duration_min: number;
  avg_pace_str: string | null;
  source: string;
}

export interface LinkCompletedRequest {
  completed_id: string;
}

// Feat C — start-date reset
export interface StartDateRequest {
  new_start_date: IsoDate;
}

export interface StartDateImpact {
  completed_kept: number;
  completed_dropped: number;
  done_planned_kept: number;
  skipped_planned_kept: number;
  planned_dropped: number;
  proposals_discarded: number;
  new_cycle1_weeks: number;
  new_cycle1_start: IsoDate;
  new_cycle1_end: IsoDate;
}

export interface StartDateResponse {
  dry_run: boolean;
  impact: StartDateImpact;
  plan: PlanCurrentOut | null;
}
