"""initial schema

Revision ID: 4d8260ee9eff
Revises: 
Create Date: 2026-05-04 00:23:03.690029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d8260ee9eff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('hr_zones_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pace_targets_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('injury_notes_md', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('completed_workouts',
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('garmin_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.Column('family', sa.Enum('running', 'strength', 'other', name='workout_family'), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_hr', sa.SmallInteger(), nullable=True),
    sa.Column('max_hr', sa.SmallInteger(), nullable=True),
    sa.Column('avg_pace_s_per_km', sa.SmallInteger(), nullable=True),
    sa.Column('elevation_gain_m', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('calories', sa.SmallInteger(), nullable=True),
    sa.Column('fit_file_path', sa.Text(), nullable=True),
    sa.Column('raw_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garmin_activity_id')
    )
    op.create_table('daily_metrics',
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_duration_s', sa.Integer(), nullable=True),
    sa.Column('hrv_overnight_ms', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('resting_hr', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_high', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_low', sa.SmallInteger(), nullable=True),
    sa.Column('training_readiness', sa.SmallInteger(), nullable=True),
    sa.Column('training_status', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'metric_date')
    )
    op.create_table('garmin_auth_state',
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('token_dir_path', sa.Text(), nullable=False),
    sa.Column('last_successful_sync', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('needs_reauth', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id')
    )
    op.create_table('plans',
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('philosophy_md', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sequence', sa.SmallInteger(), nullable=False),
    sa.Column('race_name', sa.Text(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('peak_week_target', sa.SmallInteger(), nullable=True),
    sa.Column('notes_md', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_workouts',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.Enum('easy', 'long', 'tempo', 'intervals', 'hills', 'mp_long', 'recovery', 'strides', 'strength_a', 'strength_b', 'cross', 'rest', 'race', name='workout_type'), nullable=False),
    sa.Column('family', sa.Enum('running', 'strength', 'other', name='workout_family'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'moved', 'skipped', 'done', name='workout_status'), server_default='planned', nullable=False),
    sa.Column('duration_min', sa.SmallInteger(), nullable=True),
    sa.Column('distance_mi', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('target_pace', sa.Text(), nullable=True),
    sa.Column('target_hr_zone', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('intent_md', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliations',
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('planned_id', sa.UUID(), nullable=True),
    sa.Column('completed_id', sa.UUID(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('deviation_notes_md', sa.Text(), server_default='', nullable=False),
    sa.Column('agent_review_md', sa.Text(), nullable=True),
    sa.Column('agent_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('planned_id IS NOT NULL OR completed_id IS NOT NULL', name='recon_at_least_one'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_id'], ['completed_workouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['planned_id'], ['planned_workouts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_messages',
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.Enum('daily_coach', 'plan_adapter', 'run_analyst', 'user_chat', name='agent_kind'), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('context_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_workout_id', sa.UUID(), nullable=True),
    sa.Column('related_reconciliation_id', sa.UUID(), nullable=True),
    sa.Column('proposal_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_reconciliation_id'], ['reconciliations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_workout_id'], ['planned_workouts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_messages')
    op.drop_table('reconciliations')
    op.drop_table('planned_workouts')
    op.drop_table('cycles')
    op.drop_table('plans')
    op.drop_table('garmin_auth_state')
    op.drop_table('daily_metrics')
    op.drop_table('completed_workouts')
    op.drop_table('athletes')
    # ### end Alembic commands ###
