"""make garmin_activity_id nullable

Revision ID: b50575bdea6b
Revises: e4a65bd4db7b
Create Date: 2026-05-06 21:57:18.871147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50575bdea6b'
down_revision: Union[str, None] = 'e4a65bd4db7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_workouts', 'garmin_activity_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_workouts', 'garmin_activity_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
