"""add original_snapshot_json

Revision ID: e4a65bd4db7b
Revises: 4d8260ee9eff
Create Date: 2026-05-05 22:35:33.106125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a65bd4db7b'
down_revision: Union[str, None] = '4d8260ee9eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_workouts', sa.Column('original_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_workouts', 'original_snapshot_json')
    # ### end Alembic commands ###
